"""empty message

Revision ID: 483d1ac0ee61
Revises: 
Create Date: 2026-07-12 10:43:06.058109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483d1ac0ee61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
